from __future__ import annotations

from typing import Protocol

from wuwa_ua.types import SubtitleLine


class Display(Protocol):
    def show(self, line: SubtitleLine, background: object | None = None) -> None: ...
    def pending(self, background: object | None = None) -> None: ...
    def clear(self) -> None: ...
    def run(self) -> None: ...
